[ClassVersion("1.0.0.0"), FriendlyName("xDnsRecordMx")]
class MSFT_xDnsRecordMx : OMI_BaseResource
{
    [Key, Description("Specifies the name of the DNS server resource record object. For records in the apex of the domain, use a period.")] string Name;
    [Key, Description("Specifies the name of a DNS zone.")] string Zone;
    [Key, Description("Specifies the Target Hostname or IP Address.")] string Target;
    [Required, Description("Specifies the Priority value of the MX record.")] UInt16 Priority;
    [Write, Description("Specifies the TTL value of the MX record. Value must be in valid TimeSpan format.")] string TTL;
    [Write, Description("Name of the DnsServer to create the record on.")] string DnsServer;
    [Write, Description("Should this DNS resource record be present or absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
